-- ADD THIS CODE IN OX_INVENTORY items.lua

['bandage'] = {
    label = 'Bandage',
    weight = 0,
    description = 'Can be directly used in the inventory, stops bleeding from wounds and increases health',
	stack = true,
},
['ifak'] = {
    label = 'IFAK',
    weight = 200,
    description = 'Can be directly used in the inventory, contains first aid kit',
	stack = true,
	close = true,
},
['painkillers'] = {
    label = 'Painkillers',
    weight = 0,
    description = 'Can be directly used in the inventory to reduce pain and stress',
	stack = true,
	close = true,
},
['temporary_tourniquet'] = {
    label = 'Temporary Tourniquet',
    weight = 10,
    description = 'A temporary tourniquet that can directly be used in the inventory to stop bleeding',
	stack = true,
	close = true,
},
['pager'] = {
    label = 'Pager',
    weight = 10,
    description = 'Used to inform medical staff at the hospital of an incoming patient',
	stack = false,
	close = true,
},
['tourniquet'] = {
    label = 'Tourniquet',
    weight = 10,
	stack = true,
},
['field_dressing'] = {
    label = 'Field Dressing',
    weight = 10,
	stack = true,
},
['elastic_bandage'] = {
    label = 'Elastic Bandage',
    weight = 10,
	stack = true,
},
['quick_clot'] = {
    label = 'Quick Clot',
    weight = 10,
	stack = true,
},
['packing_bandage'] = {
    label = 'Packing Bandage',
    weight = 10,
	stack = true,
},
['sewing_kit'] = {
    label = 'Sewing Kit',
    weight = 10,
	stack = true,
},
['epinephrine'] = {
    label = 'Epinephrine',
    weight = 10,
    description = 'Epinephrine, also known as adrenaline, increases the body\'s pulse as well as suppress pain.',
	stack = true,
},
['morphine'] = {
    label = 'Morphine',
    weight = 10,
    description = 'Morphine decreases the body\'s pulse as well as suppress pain.',
	stack = true,
},
['propofol'] = {
    label = 'Propofol',
    weight = 10,
    description = 'Propofol, is a powerful sedation medication.',
	stack = true,
},
['blood250ml'] = {
    label = 'Blood Pack 250ml',
    weight = 10,
	stack = true,
},
['blood500ml'] = {
    label = 'Blood Pack 500ml',
    weight = 10,
	stack = true,
},
['saline250ml'] = {
    label = 'Saline 250ml',
    weight = 10,
	stack = true,
},
['saline500ml'] = {
    label = 'Saline 500ml',
    weight = 10,
	stack = true,
},
['revivekit'] = {
    label = 'Emergency Revive Kit',
    weight = 10,
	stack = true,
},
['stretcher'] = {
    label = 'Stretcher',
    weight = 1000,
    description = 'A medical stretcher to carry wounded patients',
	stack = true,
},
['wheelchair'] = {
    label = 'Wheelchair',
    weight = 1000,
	stack = true,
},
['crutch'] = {
    label = 'Crutch',
    weight = 1000,
	stack = true,
},
['bodybag'] = {
    label = 'Bodybag',
    weight = 1000,
    description = 'A bag to put dead bodies in',
	stack = true,
},
['ecg'] = {
    label = 'ECG',
    weight = 200,
	stack = false,
	close = true,
    description = 'Electrocardiography is an electrophysiological examination method of the heart where the heart\'s electrical activity is recorded by electrodes connected to an ECG device.',
},
['neckbrace'] = {
        label = 'Neck Brace',
        weight = 1000,
        description = '',
		stack = true,
},
   ['neckcast'] = {
        label = 'Neck Cast',
        weight = 1000,
        description = '',
		stack = true,
},
   ['legsplint'] = {
        label = 'Leg Splint',
        weight = 1000,
        description = '',
		stack = true,
},
   ['legcast'] = {
        label = 'Leg Cast',
        weight = 1000,
        description = '',
		stack = true,
},
   ['armsplint'] = {
        label = 'Arm Splint',
        weight = 1000,
        description = '',
		stack = true,
},
   ['armcast'] = {
        label = 'Arm Cast',
        weight = 1000,
        description = '',
		stack = true,
},
   ['propofol'] = {
        label = 'Propofol',
        weight = 1000,
        description = '',
		stack = true,
},
['castsaw'] = {
    label = 'Cast Saw',
    weight = 10,
    description = '',
    stack = true,
},