document.addEventListener('DOMContentLoaded', () => {
  const request = window.EMSRequestForm?.create({
    generatedMessage: 'Prioritaire ortho / revalidatie aanvraag gegenereerd.',
    buildSummary: ({ getValue, joinLines }) => joinLines([
      '=== PRIORITAIRE ORTHO / REVALIDATIE AANVRAAG ===',
      `Patiënt: ${getValue('patientName') || '-'}`, `Geboortedatum: ${getValue('patientDob') || '-'}`, `Aanvrager: ${getValue('aanvrager') || '-'}`, `Locatie: ${getValue('locatie') || '-'}`, `Urgentie: ${getValue('urgentie') || '-'}`, `Type letsel / casus: ${getValue('casusType') || '-'}`, `Mobiliteit: ${getValue('mobiliteit') || '-'}`, `Prioriteit: ${getValue('prioriteit') || '-'}`, '', 'Situatieschets:', getValue('situatie') || '-', '', `Belastbaarheid: ${getValue('belastbaarheid') || '-'}`, `Betrokken zone / hulpmiddel: ${getValue('betrokkenZone') || '-'}`, `Reeds ondernomen zorgen: ${getValue('reedsGedaan') || '-'}`, `Verwachte vervolgflow: ${getValue('doorverwijzing') || '-'}`, '', 'Extra info:', getValue('extraInfo') || '-', '', 'Advies: open de revalidatie-assistent om herstelplan, hulpmiddelen en opvolging verder uit te werken.'
    ])
  });
  if (!request) return;
  if (window.DepartmentFlow) {
    DepartmentFlow.init({ departmentKey: 'revalidatie', label: 'ortho / revalidatie', stage: 'request', nextUrl: '../revalidatie-tool/index.html', steps: [{ id: 'request', title: '1. Aanvraag', shortTitle: 'aanvraag', url: window.location.pathname }, { id: 'tool', title: '2. Tool', shortTitle: 'tool', url: '../revalidatie-tool/index.html' }, { id: 'report', title: '3. Rapport', shortTitle: 'rapport', url: '../rapport-revalidatie/index.html' }], collectValues: () => ({ patientName: document.getElementById('patientName')?.value || '', patientDob: document.getElementById('patientDob')?.value || '', aanvrager: document.getElementById('aanvrager')?.value || '', locatie: document.getElementById('locatie')?.value || '', urgentie: document.getElementById('urgentie')?.value || '', casusType: document.getElementById('casusType')?.value || '', mobiliteit: document.getElementById('mobiliteit')?.value || '', prioriteit: document.getElementById('prioriteit')?.value || '', situatie: document.getElementById('situatie')?.value || '', belastbaarheid: document.getElementById('belastbaarheid')?.value || '', betrokkenZone: document.getElementById('betrokkenZone')?.value || '', reedsGedaan: document.getElementById('reedsGedaan')?.value || '', doorverwijzing: document.getElementById('doorverwijzing')?.value || '', extraInfo: document.getElementById('extraInfo')?.value || '' }), buildSummary: () => request.output.value.trim() || '', saveNextLabel: 'Zet klaar voor tool' });
  }
});
